name: Scott Nicholas
description: personal page

sass:
  sass_dir: assets/css/_sass
  style: :compressed

#url: https://neutronscott.github.io
permalink: /:year/:month/:title/
owner:
    name: Scott Nicholas
    twitter: neutronscott
    github: neutronscott
    disqus_shortname: scottn

ga_id: UA-34024204-2
ga_username: auto

timezone: America/New_York
